In [3]:
import pandas as pd
videos = pd.read_csv("shortform_videos.csv")
creators = pd.read_csv("shortform_creators.csv")
platforms = pd.read_csv("shortform_platforms.csv")

videos.head()

,video_id,creator_id,format_type,duration_sec,views,likes,comments,shares,watch_time,full_views,hook_watch_rate
0,v1,c39,meme,10,7693,4588,104,499,105186,3458,0.83
1,v2,c29,meme,28,2613,4399,692,92,166707,5011,0.71
2,v3,c15,reaction,40,16780,570,555,684,270609,6897,0.76
3,v4,c43,reaction,25,14065,1026,281,78,57754,15975,0.78
4,v5,c8,duet,23,10683,3772,686,621,230047,11239,0.72

In [4]:
# Calculate retention rate and sort top-performing videos
videos['retention_rate'] = videos['full_views'] / videos['views']
videos[['video_id', 'retention_rate']].sort_values(by='retention_rate', ascending=False).head()

    video_id  retention_rate
616     v617       23.585736
33       v34       21.250660
181     v182       20.274074
802     v803       18.619580
459     v460       18.130094

In [5]:
# Analyze average performance by format type
videos.groupby('format_type')[['views', 'likes', 'comments', 'shares', 'retention_rate']].mean().sort_values(by='retention_rate', ascending=False)

                    views        likes    comments      shares  retention_rate
format_type
story         9770.778894  2516.788945  509.080402  505.668342        1.792896
meme         10540.789216  2763.759804  517.833333  482.299020        1.668330
reaction     10544.645320  2501.729064  538.980296  465.753695        1.652105
tutorial     10422.534653  2495.762376  506.292079  496.054455        1.612918
duet         10375.947917  2527.937500  516.255208  495.640625        1.497282

In [6]:
# Merge video and creator data
merged = videos.merge(creators, on='creator_id')
creator_summary = merged.groupby('creator_name')[['views', 'likes', 'shares', 'retention_rate']].mean()
creator_summary.sort_values(by='retention_rate', ascending=False)

                     views        likes      shares  retention_rate
creator_name
Creator 31     8601.923077  2504.846154  391.538462        3.434670
Creator 27     6812.437500  2840.437500  584.187500        3.391129
Creator 16     8082.476190  2457.095238  515.428571        3.051944
Creator 28    11279.482759  2605.172414  453.931034        2.660041
Creator 15     9996.687500  2462.250000  551.312500        2.420087
Creator 44     8004.857143  2753.380952  444.666667        2.253877
Creator 8      7077.727273  2388.772727  513.590909        2.216023
Creator 20    11312.000000  2724.000000  408.866667        2.177580
Creator 29     9388.947368  3209.263158  446.947368        2.142569
Creator 37     9346.040000  2516.600000  618.560000        2.097965
Creator 50     9614.687500  2308.625000  523.187500        2.067186
Creator 18     8481.812500  2667.000000  538.250000        2.064647
Creator 7      7989.928571  2132.214286  378.857143        2.030954
Creator 2     10322.428571  2527.904762  397.047619        1.987266
Creator 48     9123.285714  2761.047619  480.142857        1.919870
Creator 19    12894.000000  2867.368421  414.631579        1.841415
Creator 41     9685.833333  2927.444444  443.277778        1.835298
Creator 36     9372.333333  2249.761905  665.761905        1.814199
Creator 42     9926.058824  3082.705882  521.000000        1.734150
Creator 4      9452.875000  2560.625000  501.687500        1.719408
Creator 30     8828.500000  2844.611111  473.222222        1.689197
Creator 47    11577.807692  2196.461538  440.000000        1.645064
Creator 26    10598.100000  2965.600000  441.333333        1.631259
Creator 49     9150.222222  2569.259259  494.259259        1.589082
Creator 25    12708.416667  3042.583333  404.708333        1.557088
Creator 21    11184.277778  2278.000000  557.888889        1.535409
Creator 3      8508.045455  2116.909091  554.227273        1.502123
Creator 24     9075.608696  2391.217391  494.391304        1.476283
Creator 5      9897.217391  2183.304348  532.739130        1.412191
Creator 32    12014.640000  2506.200000  535.520000        1.333321
Creator 35     9575.142857  2785.750000  460.678571        1.323077
Creator 40     9763.562500  2230.312500  383.125000        1.316832
Creator 14    10320.166667  1892.833333  528.055556        1.292977
Creator 33    11851.666667  2771.296296  525.370370        1.286178
Creator 11    12132.312500  2484.062500  578.687500        1.280752
Creator 45    10867.583333  2558.500000  506.333333        1.264903
Creator 13    11869.588235  2997.235294  438.352941        1.237578
Creator 10     9084.250000  2547.625000  418.937500        1.211470
Creator 23    12029.695652  2377.391304  493.521739        1.206903
Creator 6     11822.235294  1799.941176  477.117647        1.196558
Creator 1     10998.708333  2421.791667  606.708333        1.192470
Creator 34    12017.055556  2421.611111  429.555556        1.186324
Creator 17    11210.363636  3089.681818  569.090909        1.148670
Creator 12    11983.380952  2665.142857  416.000000        1.039476
Creator 43    12086.454545  3162.000000  505.727273        1.008440
Creator 46    11547.538462  2598.153846  420.230769        0.969893
Creator 9     11598.117647  2272.647059  401.117647        0.930853
Creator 38    12419.642857  2583.642857  454.928571        0.883874
Creator 39    10122.120000  2520.320000  476.440000        0.851748
Creator 22    12050.380952  2197.000000  505.000000        0.796258

In [7]:
# Evaluate hook performance across videos
videos[['video_id', 'hook_watch_rate']].sort_values(by='hook_watch_rate', ascending=False).head()

    video_id  hook_watch_rate
324     v325              1.0
312     v313              1.0
726     v727              1.0
18       v19              1.0
525     v526              1.0